(define (apply-mask)
    (let* 
        ((filelist (cadr (file-glob "*.xcf" 1))))
		(while (not (null? filelist))
            (let* (;variaveis locais
                    (filename (car filelist))
                    (only_filename (substring filename 0 (- (string-length filename) 4)))
                    (image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
                    (layer (car (gimp-image-get-layer-by-name image "exsiccata")))
                    (layer_mask (car (gimp-image-get-layer-by-name image "new-mask")))
                    (width (car (gimp-image-width image)))
                    (height (car (gimp-image-height image)))
                    (new-layer (car (gimp-layer-new image width height RGB-IMAGE "bg" 100 LAYER-MODE-NORMAL)))
                    (drawable (car (gimp-image-active-drawable image)))
                    (nfilename (string-append only_filename ".jpeg"))
                )
                (gimp-message filename)
                (gimp-layer-set-opacity layer_mask 100)
                (gimp-image-insert-layer image new-layer 0 2)
                (gimp-edit-fill new-layer FILL-WHITE)
                (gimp-image-select-color image CHANNEL-OP-ADD layer_mask '(255 255 255))
                (let (
                    (mask (car (gimp-layer-create-mask layer ADD-MASK-SELECTION)))
                    )
                    (gimp-layer-add-mask layer mask)
                    (gimp-layer-set-apply-mask layer TRUE)
                )
                (gimp-image-raise-item-to-top image new-layer)
                (gimp-image-raise-item-to-top image layer)                
                (gimp-image-set-active-layer image layer)
                (gimp-layer-set-apply-mask layer TRUE)
                (gimp-layer-set-visible layer_mask FALSE)
                (gimp-selection-none image)
                (let
                    (
                        (layer-img-segmented (car (gimp-image-merge-visible-layers image CLIP-TO-IMAGE)))
                    )
                    (gimp-item-set-name layer-img-segmented "exsiccata-segmented")
                    (gimp-file-save RUN-NONINTERACTIVE image layer-img-segmented nfilename nfilename)
                )
                ; (gimp-file-save RUN-NONINTERACTIVE image drawable nfilename nfilename)
                (gimp-xcf-save RUN-NONINTERACTIVE image drawable filename filename)
                (gimp-image-delete image)
            )
            (set! filelist (cdr filelist))
        )
	)
)