(define (black-bg)
    (let* 
        ((filelist (cadr (file-glob "*.xcf" 1))))
		(while (not (null? filelist))
            (let* (;variaveis locais
                    (filename (car filelist))
                    (image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
                    (only_filename (substring filename 0 (- (string-length filename) 4)))
                    (layer (car (gimp-image-get-layer-by-name image "exsiccata")))
                    (layer_mask (car (gimp-image-get-layer-by-name image "mask")))
                    (width (car (gimp-image-width image)))
                    (height (car (gimp-image-height image)))
                    (new-layer (car (gimp-layer-new image width height RGB-IMAGE "new-mask" 100 LAYER-MODE-NORMAL)))
                    (drawable (car (gimp-image-active-drawable image)))
                    (nfilename (string-append only_filename ".jpeg"))
                )
                (gimp-message filename)
                (gimp-selection-none image)
                (gimp-layer-set-opacity layer_mask 100)
                (gimp-image-insert-layer image new-layer 0 1)
                ; (gimp-image-convert-indexed image CONVERT-DITHER-FS CONVERT-PALETTE-MONO 0 0 1 "a")
                (let (
                    (drawable (car (gimp-image-merge-down image layer_mask CLIP-TO-IMAGE)))
                    )
                    (gimp-drawable-threshold drawable HISTOGRAM-VALUE 0.5 1)
                    (gimp-xcf-save RUN-NONINTERACTIVE image drawable filename filename)
                )                
                (gimp-image-delete image)
            )
            (set! filelist (cdr filelist))
        )
	)
)